FROM continuumio/miniconda3

WORKDIR /opt/env
COPY myenv.yml .

# 建立 Conda 環境
RUN conda env create -f myenv.yml || cat /opt/conda/pkgs/.conda-build.log

# 設定 PATH
ENV PATH=/opt/conda/envs/myenv/bin:$PATH

# 安裝工具
RUN conda install -n myenv -c conda-forge \
    notebook \
    jupyterlab \
    ipykernel \
    matplotlib \
    pandas \
    seaborn \
    plotly \
    mkdocs \
    mkdocs-material \
    pip \
    && conda run -n myenv pip install mkdocs-mermaid2-plugin pymdown-extensions \
    && apt update && apt install -y nodejs npm \
    && npm install -g @mermaid-js/mermaid-cli \

EXPOSE 8888
CMD ["bash"]
